/**
 * 各内置平台的默认模型清单 —— `catalog.ts` 的 `PROVIDER_CATALOG` 引用这里的数组。
 *
 * 拆出的原因：`AGENTS.md` 规定单文件 1500 行硬上限。模型清单是纯数据且体积最大，
 * 单独成文件后，新增平台只需在两处各加一条(此处 + `catalog.ts` 的平台元数据)。
 * 用 `Record<CatalogProviderType, ...>` 保证穷尽：漏一个平台会编译失败。
 */
import type { AIModelConfig, ProviderType } from './types.js';

type CatalogProviderType = Exclude<ProviderType, 'custom'>;

export const CATALOG_DEFAULT_MODELS: Record<CatalogProviderType, AIModelConfig[]> = {
  anthropic: [
    {
      id: 'claude-opus-4-0',
      label: 'Claude Opus 4',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 15,
      outputPricePerMillion: 75,
    },
    {
      id: 'claude-sonnet-4-0',
      label: 'Claude Sonnet 4',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 3,
      outputPricePerMillion: 15,
    },
    {
      id: 'claude-haiku-4-5',
      label: 'Claude Haiku 4.5',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 1,
      outputPricePerMillion: 5,
    },
    {
      id: 'claude-3-7-sonnet-20250219',
      label: 'Claude Sonnet 3.7',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 3,
      outputPricePerMillion: 15,
    },
    {
      id: 'claude-3-5-haiku-20241022',
      label: 'Claude Haiku 3.5',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.8,
      outputPricePerMillion: 4,
    },
  ],
  openai: [
    {
      id: 'gpt-5.6-sol',
      label: 'GPT-5.6 Sol',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
    },
    {
      id: 'gpt-5.6-terra',
      label: 'GPT-5.6 Terra',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
    },
    {
      id: 'gpt-5.6-luna',
      label: 'GPT-5.6 Luna',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
    },
    {
      id: 'gpt-5.5',
      label: 'GPT-5.5',
      enabled: true,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 5,
      outputPricePerMillion: 30,
    },
    {
      id: 'gpt-5.4',
      label: 'GPT-5.4',
      enabled: true,
      contextWindow: 1_050_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 2.5,
      outputPricePerMillion: 15,
    },
    {
      id: 'gpt-5.4-mini',
      label: 'GPT-5.4 mini',
      enabled: true,
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 0.75,
      outputPricePerMillion: 4.5,
    },
    {
      id: 'gpt-5.4-nano',
      label: 'GPT-5.4 nano',
      enabled: true,
      contextWindow: 400_000,
      maxOutputTokens: 128_000,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 0.2,
      outputPricePerMillion: 1.25,
    },
    {
      id: 'gpt-4.1',
      label: 'GPT-4.1',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 2,
      outputPricePerMillion: 8,
    },
    {
      id: 'gpt-4.1-mini',
      label: 'GPT-4.1 mini',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.4,
      outputPricePerMillion: 1.6,
    },
    {
      id: 'gpt-4.1-nano',
      label: 'GPT-4.1 nano',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.1,
      outputPricePerMillion: 0.4,
    },
    {
      id: 'o3',
      label: 'o3',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 2,
      outputPricePerMillion: 8,
    },
    {
      id: 'o4-mini',
      label: 'o4-mini',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 1.1,
      outputPricePerMillion: 4.4,
    },
    {
      id: 'gpt-4o',
      label: 'GPT-4o',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 2.5,
      outputPricePerMillion: 10,
    },
    {
      id: 'gpt-4o-mini',
      label: 'GPT-4o mini',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.15,
      outputPricePerMillion: 0.6,
    },
    {
      id: 'gpt-image-2',
      label: 'GPT Image 2',
      enabled: true,
      supportsImageGeneration: true,
      supportsImageGeneration4K: false,
    },
  ],
  deepseek: [
    {
      id: 'deepseek-chat',
      label: 'DeepSeek Chat (V3)',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 0.28,
      outputPricePerMillion: 0.42,
    },
    {
      id: 'deepseek-reasoner',
      label: 'DeepSeek Reasoner (R1)',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 0.28,
      outputPricePerMillion: 0.42,
    },
  ],
  gemini: [
    {
      id: 'gemini-2.5-pro',
      label: 'Gemini 2.5 Pro',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 1.25,
      outputPricePerMillion: 10,
    },
    {
      id: 'gemini-2.5-flash',
      label: 'Gemini 2.5 Flash',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 0.3,
      outputPricePerMillion: 2.5,
    },
    {
      id: 'gemini-2.5-flash-lite',
      label: 'Gemini 2.5 Flash Lite',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.1,
      outputPricePerMillion: 0.4,
    },
    {
      id: 'gemini-2.0-flash',
      label: 'Gemini 2.0 Flash',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.1,
      outputPricePerMillion: 0.4,
    },
  ],
  ollama: [
    {
      id: 'qwen3:8b',
      label: 'Qwen3 8B (local)',
      enabled: true,
      supportsTools: false,
      inputPricePerMillion: 0,
      outputPricePerMillion: 0,
    },
    {
      id: 'llama3.1:8b',
      label: 'Llama 3.1 8B (local)',
      enabled: true,
      supportsTools: false,
      inputPricePerMillion: 0,
      outputPricePerMillion: 0,
    },
  ],
  openrouter: [
    {
      id: 'anthropic/claude-sonnet-4-0',
      label: 'Claude Sonnet 4 (OpenRouter)',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 3,
      outputPricePerMillion: 15,
    },
    {
      id: 'openai/gpt-4.1',
      label: 'GPT-4.1 (OpenRouter)',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 2,
      outputPricePerMillion: 8,
    },
    {
      id: 'openai/gpt-5',
      label: 'GPT-5 (OpenRouter)',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 1.25,
      outputPricePerMillion: 10,
    },
    {
      id: 'google/gemini-2.5-pro',
      label: 'Gemini 2.5 Pro (OpenRouter)',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 1.25,
      outputPricePerMillion: 10,
    },
    {
      id: 'deepseek/deepseek-chat-v3-0324',
      label: 'DeepSeek V3 (OpenRouter)',
      enabled: true,
      supportsTools: true,
      inputPricePerMillion: 0.28,
      outputPricePerMillion: 0.88,
    },
    {
      id: 'openai/gpt-4o-mini',
      label: 'GPT-4o mini (OpenRouter)',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 0.15,
      outputPricePerMillion: 0.6,
    },
  ],
  qwen: [
    {
      id: 'qwen3-235b-a22b',
      label: 'Qwen3 235B-A22B',
      enabled: true,
      supportsTools: true,
      supportsVision: false,
      supportsThinking: true,
      inputPricePerMillion: 0.7,
      outputPricePerMillion: 2.8,
    },
    {
      id: 'qwen-max',
      label: 'Qwen Max',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      inputPricePerMillion: 1.6,
      outputPricePerMillion: 6.4,
    },
    {
      id: 'qwen-plus',
      label: 'Qwen Plus',
      enabled: true,
      supportsTools: true,
      supportsVision: false,
      inputPricePerMillion: 0.4,
      outputPricePerMillion: 1.2,
    },
    {
      id: 'qwen-turbo',
      label: 'Qwen Turbo',
      enabled: true,
      supportsTools: true,
      supportsVision: false,
      inputPricePerMillion: 0.05,
      outputPricePerMillion: 0.2,
    },
    {
      id: 'qwq-plus',
      label: 'QwQ Plus',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 0.8,
      outputPricePerMillion: 2.4,
    },
  ],
  moonshot: [
    {
      id: 'kimi-k2.5',
      label: 'Kimi K2.5',
      enabled: true,
      supportsTools: true,
      supportsVision: false,
      supportsThinking: true,
      inputPricePerMillion: 0.6,
      outputPricePerMillion: 3,
    },
    {
      id: 'kimi-k2-thinking',
      label: 'Kimi K2 Thinking',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 0.6,
      outputPricePerMillion: 2.5,
    },
    {
      id: 'kimi-k2-turbo-preview',
      label: 'Kimi K2 Turbo',
      enabled: true,
      supportsTools: true,
      inputPricePerMillion: 2.4,
      outputPricePerMillion: 10,
    },
  ],
  mimo: [
    {
      id: 'mimo-v2.5-pro',
      label: 'MiMo V2.5 Pro',
      enabled: true,
      contextWindow: 1_000_000,
      maxOutputTokens: 131072,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 1,
      outputPricePerMillion: 3,
    },
    {
      id: 'mimo-v2.5',
      label: 'MiMo V2.5',
      enabled: true,
      contextWindow: 1_000_000,
      maxOutputTokens: 131072,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      inputPricePerMillion: 0.4,
      outputPricePerMillion: 2,
    },
    {
      id: 'mimo-v2-flash',
      label: 'MiMo V2 Flash',
      enabled: true,
      contextWindow: 256_000,
      maxOutputTokens: 65536,
      supportsTools: true,
      supportsThinking: true,
      inputPricePerMillion: 0.1,
      outputPricePerMillion: 0.3,
    },
  ],
  mistral: [
    {
      id: 'mistral-large-latest',
      label: 'Mistral Large',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'mistral-small-latest',
      label: 'Mistral Small',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'codestral-latest',
      label: 'Codestral',
      enabled: true,
      supportsTools: true,
    },
  ],
  zhipu: [
    {
      id: 'glm-4.5',
      label: 'GLM-4.5',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'glm-4-flash',
      label: 'GLM-4 Flash',
      enabled: true,
      supportsTools: true,
    },
  ],
  doubao: [
    {
      id: 'ep-your-endpoint-id',
      label: '（请替换为方舟接入点 ID）',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'doubao-seed-1.6',
      label: 'Doubao Seed 1.6',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
  ],
  groq: [
    {
      id: 'llama-3.3-70b-versatile',
      label: 'Llama 3.3 70B Versatile',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'llama-3.1-8b-instant',
      label: 'Llama 3.1 8B Instant',
      enabled: true,
      supportsTools: true,
    },
  ],
  siliconflow: [
    {
      id: 'deepseek-ai/DeepSeek-V3',
      label: 'DeepSeek V3',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'Qwen/Qwen2.5-7B-Instruct',
      label: 'Qwen2.5 7B Instruct',
      enabled: true,
      supportsTools: true,
    },
  ],
  azure: [
    {
      id: 'gpt-4o',
      label: '（部署名请改成你的 deployment）',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
    },
    {
      id: 'gpt-5',
      label: 'GPT-5（部署名请改成你的 deployment）',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
    },
  ],
  xai: [
    {
      id: 'grok-3',
      label: 'Grok 3',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'grok-3-mini',
      label: 'Grok 3 Mini',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
  ],
  minimax: [
    {
      id: 'MiniMax-Text-01',
      label: 'MiniMax Text 01',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'abab6.5s-chat',
      label: 'ABAB 6.5s Chat',
      enabled: true,
      supportsTools: true,
    },
  ],
  baichuan: [
    {
      id: 'Baichuan4',
      label: 'Baichuan 4',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'Baichuan3-Turbo',
      label: 'Baichuan 3 Turbo',
      enabled: true,
      supportsTools: true,
    },
  ],
  hunyuan: [
    {
      id: 'hunyuan-turbos-latest',
      label: 'Hunyuan TurboS',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'hunyuan-lite',
      label: 'Hunyuan Lite',
      enabled: true,
      supportsTools: true,
    },
  ],
  qianfan: [
    {
      id: 'ernie-4.0-8k',
      label: 'ERNIE 4.0 8K',
      enabled: true,
      supportsTools: true,
    },
    {
      id: 'ernie-speed-8k',
      label: 'ERNIE Speed 8K',
      enabled: true,
      supportsTools: true,
    },
  ],
  'opencode-go': [
    {
      id: 'grok-4.6',
      label: 'Grok 4.6',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['low', 'medium', 'high', 'xhigh'] }],
    },
    {
      id: 'gpt-5.6-luna',
      label: 'GPT-5.6 Luna',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [
        { type: 'effort', values: ['none', 'low', 'medium', 'high', 'xhigh', 'max'] },
      ],
    },
    {
      id: 'glm-5.3-flash',
      label: 'GLM-5.3-Flash',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['low', 'high', 'max'] }],
    },
    {
      id: 'glm-5.3',
      label: 'GLM-5.3',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['low', 'high', 'max'] }],
    },
    {
      id: 'glm-5.2',
      label: 'GLM-5.2',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['high', 'max'] }],
    },
    {
      id: 'glm-5.1',
      label: 'GLM-5.1',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'kimi-k3',
      label: 'Kimi K3',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['max'] }],
    },
    {
      id: 'kimi-k2.7-code',
      label: 'Kimi K2.7 Code',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'kimi-k2.6',
      label: 'Kimi K2.6',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'longcat-2.0',
      label: 'LongCat-2.0',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }],
    },
    {
      id: 'deepseek-v4.1-flash',
      label: 'DeepSeek V4.1 Flash',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['low', 'high', 'max'] }],
    },
    {
      id: 'deepseek-v4-pro',
      label: 'DeepSeek V4 Pro',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['high', 'max'] }],
    },
    {
      id: 'deepseek-v4-flash',
      label: 'DeepSeek V4 Flash',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['low', 'high', 'max'] }],
    },
    {
      id: 'deepseek-v4-flash-vision-exp',
      label: 'DeepSeek V4 Flash Vision Exp',
      enabled: true,
      supportsTools: true,
      supportsVision: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }, { type: 'effort', values: ['low', 'high', 'max'] }],
    },
    {
      id: 'mimo-v2.5',
      label: 'MiMo V2.5',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'mimo-v2.5-pro',
      label: 'MiMo V2.5 Pro',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'minimax-m3',
      label: 'MiniMax M3',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }],
    },
    {
      id: 'minimax-m2.7',
      label: 'MiniMax M2.7',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'minimax-m2.5',
      label: 'MiniMax M2.5',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
    },
    {
      id: 'qwen3.8-max',
      label: 'Qwen3.8 Max',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [
        { type: 'toggle' },
        { type: 'effort', values: ['low', 'medium', 'xhigh'] },
        { type: 'budget_tokens' },
      ],
    },
    {
      id: 'qwen3.8-flash',
      label: 'Qwen3.8 Flash',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [
        { type: 'toggle' },
        { type: 'effort', values: ['low', 'medium', 'xhigh'] },
        { type: 'budget_tokens' },
      ],
    },
    {
      id: 'qwen3.7-max',
      label: 'Qwen3.7 Max',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }, { type: 'budget_tokens' }],
    },
    {
      id: 'qwen3.7-plus',
      label: 'Qwen3.7 Plus',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }, { type: 'budget_tokens' }],
    },
    {
      id: 'qwen3.6-plus',
      label: 'Qwen3.6 Plus',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'toggle' }, { type: 'budget_tokens' }],
    },
    {
      id: 'muse-spark-1.3-contributor',
      label: 'Muse Spark 1.3 Contributor',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['minimal', 'low', 'medium', 'high', 'xhigh'] }],
    },
    {
      id: 'muse-spark-1.2-contributor',
      label: 'Muse Spark 1.2 Contributor',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['minimal', 'low', 'medium', 'high', 'xhigh'] }],
    },
    {
      id: 'hy4-preview',
      label: 'Hy4 preview',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['none', 'high'] }],
    },
    {
      id: 'hy3',
      label: 'Hy3',
      enabled: true,
      supportsTools: true,
      supportsThinking: true,
      reasoningOptions: [{ type: 'effort', values: ['none', 'low', 'high'] }],
    },
  ],
};
