import type { AIProvider, ProviderType } from './types.js';

export type BuiltinProviderType = Exclude<ProviderType, 'custom'>;

type ProviderPreset = Omit<AIProvider, 'createdAt' | 'updatedAt'>;

const BUILTIN_PRESETS: Record<BuiltinProviderType, ProviderPreset> = {
  anthropic: {
    id: 'anthropic',
    type: 'anthropic',
    name: 'Anthropic',
    enabled: true,
    baseUrl: 'https://api.anthropic.com/v1',
    apiKeyEnv: 'ANTHROPIC_API_KEY',
    defaultModels: [
      {
        id: 'claude-opus-4-0',
        label: 'Claude Opus 4',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 15,
        outputPricePerMillion: 75,
      },
      {
        id: 'claude-sonnet-4-0',
        label: 'Claude Sonnet 4',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 3,
        outputPricePerMillion: 15,
      },
      {
        id: 'claude-haiku-4-5',
        label: 'Claude Haiku 4.5',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 1,
        outputPricePerMillion: 5,
      },
      {
        id: 'claude-3-7-sonnet-20250219',
        label: 'Claude Sonnet 3.7',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 3,
        outputPricePerMillion: 15,
      },
      {
        id: 'claude-3-5-haiku-20241022',
        label: 'Claude Haiku 3.5',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.8,
        outputPricePerMillion: 4,
      },
    ],
  },
  openai: {
    id: 'openai',
    type: 'openai',
    name: 'OpenAI',
    enabled: true,
    baseUrl: 'https://api.openai.com/v1',
    apiKeyEnv: 'OPENAI_API_KEY',
    defaultModels: [
      {
        id: 'gpt-4.1',
        label: 'GPT-4.1',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 2,
        outputPricePerMillion: 8,
      },
      {
        id: 'gpt-4.1-mini',
        label: 'GPT-4.1 mini',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.4,
        outputPricePerMillion: 1.6,
      },
      {
        id: 'gpt-4.1-nano',
        label: 'GPT-4.1 nano',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.1,
        outputPricePerMillion: 0.4,
      },
      {
        id: 'o3',
        label: 'o3',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 2,
        outputPricePerMillion: 8,
      },
      {
        id: 'o4-mini',
        label: 'o4-mini',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 1.1,
        outputPricePerMillion: 4.4,
      },
      {
        id: 'gpt-4o',
        label: 'GPT-4o',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 2.5,
        outputPricePerMillion: 10,
      },
      {
        id: 'gpt-4o-mini',
        label: 'GPT-4o mini',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.15,
        outputPricePerMillion: 0.6,
      },
    ],
  },
  deepseek: {
    id: 'deepseek',
    type: 'deepseek',
    name: 'DeepSeek',
    enabled: true,
    baseUrl: 'https://api.deepseek.com',
    apiKeyEnv: 'DEEPSEEK_API_KEY',
    defaultModels: [
      {
        id: 'deepseek-chat',
        label: 'DeepSeek Chat (V3)',
        enabled: true,
        supportsTools: true,
        supportsThinking: true,
        inputPricePerMillion: 0.28,
        outputPricePerMillion: 0.42,
      },
      {
        id: 'deepseek-reasoner',
        label: 'DeepSeek Reasoner (R1)',
        enabled: true,
        supportsTools: true,
        supportsThinking: true,
        inputPricePerMillion: 0.28,
        outputPricePerMillion: 0.42,
      },
    ],
  },
  gemini: {
    id: 'gemini',
    type: 'gemini',
    name: 'Google Gemini',
    enabled: true,
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    apiKeyEnv: 'GEMINI_API_KEY',
    defaultModels: [
      {
        id: 'gemini-2.5-pro',
        label: 'Gemini 2.5 Pro',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 1.25,
        outputPricePerMillion: 10,
      },
      {
        id: 'gemini-2.5-flash',
        label: 'Gemini 2.5 Flash',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        supportsThinking: true,
        inputPricePerMillion: 0.3,
        outputPricePerMillion: 2.5,
      },
      {
        id: 'gemini-2.5-flash-lite',
        label: 'Gemini 2.5 Flash Lite',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.1,
        outputPricePerMillion: 0.4,
      },
      {
        id: 'gemini-2.0-flash',
        label: 'Gemini 2.0 Flash',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.1,
        outputPricePerMillion: 0.4,
      },
    ],
  },
  ollama: {
    id: 'ollama',
    type: 'ollama',
    name: 'Ollama',
    enabled: false,
    baseUrl: 'http://localhost:11434/v1',
    defaultModels: [
      {
        id: 'qwen3:8b',
        label: 'Qwen3 8B (local)',
        enabled: true,
        supportsTools: false,
        inputPricePerMillion: 0,
        outputPricePerMillion: 0,
      },
      {
        id: 'llama3.1:8b',
        label: 'Llama 3.1 8B (local)',
        enabled: true,
        supportsTools: false,
        inputPricePerMillion: 0,
        outputPricePerMillion: 0,
      },
    ],
  },
  openrouter: {
    id: 'openrouter',
    type: 'openrouter',
    name: 'OpenRouter',
    enabled: false,
    baseUrl: 'https://openrouter.ai/api/v1',
    apiKeyEnv: 'OPENROUTER_API_KEY',
    defaultModels: [
      {
        id: 'anthropic/claude-sonnet-4-0',
        label: 'Claude Sonnet 4 (OpenRouter)',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 3,
        outputPricePerMillion: 15,
      },
      {
        id: 'openai/gpt-4.1',
        label: 'GPT-4.1 (OpenRouter)',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 2,
        outputPricePerMillion: 8,
      },
      {
        id: 'google/gemini-2.5-pro',
        label: 'Gemini 2.5 Pro (OpenRouter)',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 1.25,
        outputPricePerMillion: 10,
      },
      {
        id: 'deepseek/deepseek-chat-v3-0324',
        label: 'DeepSeek V3 (OpenRouter)',
        enabled: true,
        supportsTools: true,
        inputPricePerMillion: 0.28,
        outputPricePerMillion: 0.88,
      },
      {
        id: 'openai/gpt-4o-mini',
        label: 'GPT-4o mini (OpenRouter)',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 0.15,
        outputPricePerMillion: 0.6,
      },
    ],
  },
  qwen: {
    id: 'qwen',
    type: 'qwen',
    name: 'Qwen',
    enabled: false,
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    apiKeyEnv: 'QWEN_API_KEY',
    defaultModels: [
      {
        id: 'qwen3-235b-a22b',
        label: 'Qwen3 235B-A22B',
        enabled: true,
        supportsTools: true,
        supportsVision: false,
        supportsThinking: true,
        inputPricePerMillion: 0.7,
        outputPricePerMillion: 2.8,
      },
      {
        id: 'qwen-max',
        label: 'Qwen Max',
        enabled: true,
        supportsTools: true,
        supportsVision: true,
        inputPricePerMillion: 1.6,
        outputPricePerMillion: 6.4,
      },
      {
        id: 'qwen-plus',
        label: 'Qwen Plus',
        enabled: true,
        supportsTools: true,
        supportsVision: false,
        inputPricePerMillion: 0.4,
        outputPricePerMillion: 1.2,
      },
      {
        id: 'qwen-turbo',
        label: 'Qwen Turbo',
        enabled: true,
        supportsTools: true,
        supportsVision: false,
        inputPricePerMillion: 0.05,
        outputPricePerMillion: 0.2,
      },
      {
        id: 'qwq-plus',
        label: 'QwQ Plus',
        enabled: true,
        supportsTools: true,
        supportsThinking: true,
        inputPricePerMillion: 0.8,
        outputPricePerMillion: 2.4,
      },
    ],
  },
  moonshot: {
    id: 'moonshot',
    type: 'moonshot',
    name: 'Moonshot (Kimi)',
    enabled: false,
    baseUrl: 'https://api.moonshot.cn/v1',
    apiKeyEnv: 'MOONSHOT_API_KEY',
    defaultModels: [
      {
        id: 'kimi-k2.5',
        label: 'Kimi K2.5',
        enabled: true,
        supportsTools: true,
        supportsVision: false,
        supportsThinking: true,
        inputPricePerMillion: 0.6,
        outputPricePerMillion: 3,
      },
      {
        id: 'kimi-k2-thinking',
        label: 'Kimi K2 Thinking',
        enabled: true,
        supportsTools: true,
        supportsThinking: true,
        inputPricePerMillion: 0.6,
        outputPricePerMillion: 2.5,
      },
      {
        id: 'kimi-k2-turbo-preview',
        label: 'Kimi K2 Turbo',
        enabled: true,
        supportsTools: true,
        inputPricePerMillion: 2.4,
        outputPricePerMillion: 10,
      },
    ],
  },
};

export const BUILTIN_PROVIDER_TYPES = Object.freeze(
  Object.keys(BUILTIN_PRESETS) as BuiltinProviderType[],
);

const clonePreset = (preset: ProviderPreset): ProviderPreset => ({
  ...preset,
  defaultModels: preset.defaultModels.map((model) => ({ ...model })),
  requestOverrides: preset.requestOverrides
    ? {
        ...preset.requestOverrides,
        omitBodyKeys: preset.requestOverrides.omitBodyKeys
          ? [...preset.requestOverrides.omitBodyKeys]
          : undefined,
      }
    : undefined,
});

export const getBuiltinProviderPreset = (type: BuiltinProviderType): AIProvider => {
  const now = new Date().toISOString();
  const preset = clonePreset(BUILTIN_PRESETS[type]);
  return {
    ...preset,
    createdAt: now,
    updatedAt: now,
  };
};

export const getAllBuiltinPresets = (): AIProvider[] =>
  BUILTIN_PROVIDER_TYPES.map((type) => getBuiltinProviderPreset(type));
