const CLARIFY_MODE_ALLOWED_TOOLS: ReadonlySet<string> = new Set([
  'list',
  'read',
  'glob',
  'grep',
  'read_tool_output',
  'workspace_review_status',
  'workspace_review_diff',
  'lsp_diagnostics',
  'lsp_touch',
  'lsp_goto_definition',
  'lsp_goto_implementation',
  'lsp_find_references',
  'lsp_symbols',
  'lsp_hover',
  'lsp_call_hierarchy',
  'codesearch',
  'websearch',
  'webfetch',
  'question',
  'AskUserQuestion',
  'EnterPlanMode',
  'ExitPlanMode',
  'session_list',
  'session_read',
  'session_search',
  'session_info',
  // 只读的模型检索：澄清模式下也应允许（不产生文件/网络副作用）。
  'models',
  'todoread',
  'subtodoread',
  'task_list',
  'task_get',
  'look_at',
  'task',
  'Agent',
]);

export function isClarifyModeToolAllowed(toolName: string): boolean {
  return CLARIFY_MODE_ALLOWED_TOOLS.has(toolName);
}
