/**
 * Suppress console noise produced by browser extensions injecting
 * scripts into our preview iframes.
 *
 * Why this exists:
 *   The file preview iframe uses `sandbox="allow-scripts"` with NO
 *   `allow-same-origin`, which is the correct secure default — preview
 *   content is untrusted code from disk and must not see this app's
 *   cookies/localStorage. But user-script managers (Tampermonkey,
 *   Violentmonkey), ad-blockers, and other content scripts inject
 *   themselves into every frame and try to use storage APIs, which
 *   throws `SecurityError: Failed to read the 'localStorage' property
 *   from 'Window': The document is sandboxed and lacks the
 *   'allow-same-origin' flag.`
 *
 *   These errors are 100% generated by the extension, not our code,
 *   and there's nothing for us to fix. Hiding them makes real errors
 *   visible again.
 *
 * What we DON'T do:
 *   We never patch console methods. We only listen for the global
 *   error / unhandledrejection events and call preventDefault when
 *   the source is clearly extension-injected code. Errors from our
 *   own preview content (or anything else) still surface normally.
 *
 * Idempotent: calling twice is a no-op. Safe at module load.
 */

let installed = false;

const EXTENSION_FILE_RE =
  /(?:^|\/)(?:userscript\.html|frame(?:_\w+)?\.js|content(?:_\w+)?\.js|injected(?:_\w+)?\.js)\b|\bchrome-extension:\/\/|\bmoz-extension:\/\/|\bsafari-(?:extension|web-extension):\/\//i;

const EXTENSION_MESSAGE_RE =
  /sandboxed and lacks the 'allow-same-origin' flag|userscript\.html\?name=|runtime\.lastError|Could not establish connection\. Receiving end does not exist/i;

function looksLikeExtensionNoise(meta: {
  message?: string;
  filename?: string;
  stack?: string;
}): boolean {
  if (meta.filename && EXTENSION_FILE_RE.test(meta.filename)) return true;
  if (meta.stack && EXTENSION_FILE_RE.test(meta.stack)) return true;
  if (meta.message && EXTENSION_MESSAGE_RE.test(meta.message)) return true;
  if (meta.stack && EXTENSION_MESSAGE_RE.test(meta.stack)) return true;
  return false;
}

export function installExtensionNoiseFilter(): void {
  if (installed) return;
  if (typeof window === 'undefined') return;
  installed = true;

  window.addEventListener(
    'error',
    (event) => {
      const meta = {
        message: event.message,
        filename: event.filename,
        stack:
          event.error && typeof event.error === 'object' && 'stack' in event.error
            ? String((event.error as { stack?: unknown }).stack ?? '')
            : '',
      };
      if (!looksLikeExtensionNoise(meta)) return;
      event.preventDefault();
      event.stopImmediatePropagation();
    },
    true,
  );

  window.addEventListener(
    'unhandledrejection',
    (event) => {
      const reason = event.reason;
      const message =
        typeof reason === 'string'
          ? reason
          : (reason as { message?: unknown })?.message
            ? String((reason as { message?: unknown }).message)
            : '';
      const stack =
        reason && typeof reason === 'object' && 'stack' in reason
          ? String((reason as { stack?: unknown }).stack ?? '')
          : '';
      if (!looksLikeExtensionNoise({ message, stack })) return;
      event.preventDefault();
    },
    true,
  );
}
