export const LANGUAGE_EXTENSIONS: Record<string, string> = {
  '.ts': 'typescript',
  '.tsx': 'typescriptreact',
  '.mts': 'typescript',
  '.cts': 'typescript',
  '.js': 'javascript',
  '.jsx': 'javascriptreact',
  '.mjs': 'javascript',
  '.cjs': 'javascript',
  '.json': 'json',
  '.jsonc': 'jsonc',
  '.json5': 'json5',
  '.go': 'go',
  '.py': 'python',
  '.pyi': 'python',
  '.rs': 'rust',
  '.c': 'c',
  '.h': 'c',
  '.cpp': 'cpp',
  '.cc': 'cpp',
  '.cxx': 'cpp',
  '.hpp': 'cpp',
  '.hxx': 'cpp',
  '.cs': 'csharp',
  '.java': 'java',
  '.kt': 'kotlin',
  '.kts': 'kotlin',
  '.swift': 'swift',
  '.rb': 'ruby',
  '.php': 'php',
  '.lua': 'lua',
  '.r': 'r',
  '.R': 'r',
  '.dart': 'dart',
  '.scala': 'scala',
  '.clj': 'clojure',
  '.cljs': 'clojure',
  '.ex': 'elixir',
  '.exs': 'elixir',
  '.erl': 'erlang',
  '.hrl': 'erlang',
  '.hs': 'haskell',
  '.lhs': 'haskell',
  '.ml': 'ocaml',
  '.mli': 'ocaml',
  '.sh': 'shellscript',
  '.bash': 'shellscript',
  '.zsh': 'shellscript',
  '.fish': 'fish',
  '.ps1': 'powershell',
  '.psm1': 'powershell',
  '.psd1': 'powershell',
  '.yaml': 'yaml',
  '.yml': 'yaml',
  '.toml': 'toml',
  '.xml': 'xml',
  '.html': 'html',
  '.htm': 'html',
  '.css': 'css',
  '.scss': 'scss',
  '.sass': 'sass',
  '.less': 'less',
  '.vue': 'vue',
  '.svelte': 'svelte',
  '.md': 'markdown',
  '.mdx': 'mdx',
  '.tex': 'latex',
  '.tf': 'terraform',
  '.tfvars': 'terraform',
  '.proto': 'proto',
  '.graphql': 'graphql',
  '.gql': 'graphql',
  '.sql': 'sql',
  '.dockerfile': 'dockerfile',
  '.vim': 'vim',
  '.zig': 'zig',
  '.nim': 'nim',
  '.cr': 'crystal',
  '.jl': 'julia',
  '.groovy': 'groovy',
  '.gradle': 'groovy',
  '.cmake': 'cmake',
  '.mk': 'makefile',
};

export function getLanguageId(filePath: string): string {
  const ext = filePath.slice(filePath.lastIndexOf('.'));
  const byFullName = getLanguageByFilename(filePath);
  if (byFullName) return byFullName;
  return LANGUAGE_EXTENSIONS[ext] ?? 'plaintext';
}

function getLanguageByFilename(filePath: string): string | undefined {
  const base = filePath.split('/').pop()?.toLowerCase() ?? '';
  const exact: Record<string, string> = {
    dockerfile: 'dockerfile',
    makefile: 'makefile',
    gemfile: 'ruby',
    rakefile: 'ruby',
    podfile: 'ruby',
    '.env': 'dotenv',
    '.gitignore': 'ignore',
    '.gitattributes': 'ignore',
  };
  return exact[base];
}
