/**
 * 260516-team-phase-e · T-09 / T-10 / T-11 / T-12
 *
 * 5 个内置 workflow 包。
 */

import type { TeamWorkflow } from './workflow-template-schema.js';

const QUICK_ASK: TeamWorkflow = {
  id: 'quick-ask',
  name: '快速问答',
  description: '只走接待层，不做规划/执行。适合简单问题。',
  version: '1.0.0',
  source: 'builtin',
  entryStepId: 'reception',
  steps: [
    {
      id: 'reception',
      roleLayer: 'reception',
      label: '接待',
      promptTemplate: '直接回答用户问题，不需要拆解任务。',
      toolsets: ['read', 'web'],
      handoffTargets: [],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: true,
    },
  ],
  defaultBindings: { reception: 'interaction-agent' },
  tags: ['simple', 'qa'],
};

const RESEARCH_TEAM: TeamWorkflow = {
  id: 'research-team',
  name: '研究团队',
  description: '接待→规划→执行，跳过 PM2 管控层。适合研究/探索任务。',
  version: '1.0.0',
  source: 'builtin',
  entryStepId: 'reception',
  steps: [
    {
      id: 'reception',
      roleLayer: 'reception',
      label: '接待',
      promptTemplate: '',
      toolsets: ['read', 'web'],
      handoffTargets: ['pm1'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'pm1',
      roleLayer: 'pm1',
      label: '规划',
      promptTemplate: '',
      toolsets: ['read', 'write'],
      handoffTargets: ['executor'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'executor',
      roleLayer: 'executor',
      label: '执行',
      promptTemplate: '',
      toolsets: ['read', 'write', 'shell', 'web', 'lsp', 'desktop'],
      handoffTargets: ['reviewer'],
      parallel: true,
      minInstances: 2,
      maxInstances: 6,
      gates: [],
      terminal: false,
    },
    {
      id: 'reviewer',
      roleLayer: 'reviewer',
      label: '评审',
      promptTemplate: '',
      toolsets: ['read', 'lsp', 'review'],
      handoffTargets: [],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: ['spec-review'],
      terminal: true,
    },
  ],
  defaultBindings: {
    reception: 'interaction-agent',
    pm1: 'planner',
    executor: 'executor',
    reviewer: 'reviewer',
  },
  tags: ['research', 'exploration'],
};

const BUILD_TEAM: TeamWorkflow = {
  id: 'build-team',
  name: '构建团队',
  description: '完整五层流程：接待→规划→管控→执行→评审。适合正式开发任务。',
  version: '1.0.0',
  source: 'builtin',
  entryStepId: 'reception',
  steps: [
    {
      id: 'reception',
      roleLayer: 'reception',
      label: '接待',
      promptTemplate: '',
      toolsets: ['read', 'web'],
      handoffTargets: ['pm1'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'pm1',
      roleLayer: 'pm1',
      label: '规划',
      promptTemplate: '',
      toolsets: ['read', 'write'],
      handoffTargets: ['pm2'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: ['constitution-check'],
      terminal: false,
    },
    {
      id: 'pm2',
      roleLayer: 'pm2',
      label: '管控',
      promptTemplate: '',
      toolsets: ['read', 'write', 'shell'],
      handoffTargets: ['executor', 'reviewer'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: ['constitution-check'],
      terminal: false,
    },
    {
      id: 'executor',
      roleLayer: 'executor',
      label: '执行',
      promptTemplate: '',
      toolsets: ['read', 'write', 'shell', 'lsp', 'test', 'desktop'],
      handoffTargets: ['reviewer'],
      parallel: true,
      minInstances: 2,
      maxInstances: 8,
      gates: [],
      terminal: false,
    },
    {
      id: 'reviewer',
      roleLayer: 'reviewer',
      label: '评审',
      promptTemplate: '',
      toolsets: ['read', 'lsp', 'review'],
      handoffTargets: [],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: ['spec-review', 'quality-review'],
      terminal: true,
    },
  ],
  defaultBindings: {
    reception: 'interaction-agent',
    pm1: 'planner',
    pm2: 'team-leader',
    executor: 'executor',
    reviewer: 'reviewer',
  },
  tags: ['development', 'full-team'],
};

const REVIEW_TEAM: TeamWorkflow = {
  id: 'review-team',
  name: '审查团队',
  description: '接待→规划→评审。适合代码审查/文档审查任务。',
  version: '1.0.0',
  source: 'builtin',
  entryStepId: 'reception',
  steps: [
    {
      id: 'reception',
      roleLayer: 'reception',
      label: '接待',
      promptTemplate: '',
      toolsets: ['read'],
      handoffTargets: ['pm1'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'pm1',
      roleLayer: 'pm1',
      label: '规划',
      promptTemplate: '聚焦审查目标和检查清单，不需要生成实施计划。',
      toolsets: ['read'],
      handoffTargets: ['reviewer'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'reviewer',
      roleLayer: 'reviewer',
      label: '评审',
      promptTemplate: '',
      toolsets: ['read', 'lsp', 'review'],
      handoffTargets: [],
      parallel: true,
      minInstances: 2,
      maxInstances: 4,
      gates: ['quality-review'],
      terminal: true,
    },
  ],
  defaultBindings: {
    reception: 'interaction-agent',
    pm1: 'planner',
    reviewer: 'reviewer',
  },
  tags: ['review', 'audit'],
};

const SPIKE_TEAM: TeamWorkflow = {
  id: 'spike-team',
  name: '技术探针',
  description: '接待→执行。快速验证技术可行性，跳过规划和评审。',
  version: '1.0.0',
  source: 'builtin',
  entryStepId: 'reception',
  steps: [
    {
      id: 'reception',
      roleLayer: 'reception',
      label: '接待',
      promptTemplate: '',
      toolsets: ['read', 'web'],
      handoffTargets: ['executor'],
      parallel: false,
      minInstances: 1,
      maxInstances: 1,
      gates: [],
      terminal: false,
    },
    {
      id: 'executor',
      roleLayer: 'executor',
      label: '执行',
      promptTemplate: '快速验证技术可行性，产出最小可工作原型。不需要完整实现。',
      toolsets: ['read', 'write', 'shell', 'web', 'lsp', 'desktop'],
      handoffTargets: [],
      parallel: false,
      minInstances: 1,
      maxInstances: 2,
      gates: [],
      terminal: true,
    },
  ],
  defaultBindings: {
    reception: 'interaction-agent',
    executor: 'executor',
  },
  tags: ['spike', 'prototype', 'poc'],
};

export const BUILTIN_WORKFLOWS: readonly TeamWorkflow[] = [
  QUICK_ASK,
  RESEARCH_TEAM,
  BUILD_TEAM,
  REVIEW_TEAM,
  SPIKE_TEAM,
];
