export const CHANNEL_PERMISSION_TOOL_NAMES = [
  'PluginSendMessage',
  'PluginReplyMessage',
  'PluginSendImage',
  'PluginGetGroupMessages',
  'PluginListGroups',
  'PluginSummarizeGroup',
  'PluginGetCurrentChatMessages',
  'WeixinSendImage',
  'WeixinSendFile',
  'FeishuSendImage',
  'FeishuSendFile',
  'FeishuListChatMembers',
  'FeishuAtMember',
  'FeishuSendUrgent',
  'FeishuBitableListApps',
  'FeishuBitableListTables',
  'FeishuBitableListFields',
  'FeishuBitableGetRecords',
  'FeishuBitableCreateRecords',
  'FeishuBitableUpdateRecords',
  'FeishuBitableDeleteRecords',
] as const;

const BASE_TOOL_TO_CATEGORY = {
  read: 'read',
  workspace_read_file: 'read',
  edit: 'edit',
  multi_edit: 'edit',
  apply_patch: 'edit',
  write: 'write',
  workspace_write_file: 'write',
  workspace_create_file: 'write',
  workspace_create_directory: 'write',
  bash: 'bash',
  interactive_bash: 'bash',
  glob: 'glob',
  grep: 'grep',
  task: 'task_run',
  task_create: 'task',
  task_update: 'task',
  call_omo_agent: 'task_run',
  skill: 'skill',
  skill_mcp: 'skill',
  mcp_call: 'mcp_call',
  lsp_rename: 'lsp',
  websearch: 'websearch',
  webfetch: 'webfetch',
  codesearch: 'codesearch',
  workspace_review_revert: 'edit',
  ast_grep_replace: 'edit',
  desktop_automation: 'desktop_automation',
  desktop_control: 'desktop_control',
} as const;

export const TOOL_TO_PERMISSION_CATEGORY: Readonly<Record<string, string>> = {
  ...BASE_TOOL_TO_CATEGORY,
  ...Object.fromEntries(CHANNEL_PERMISSION_TOOL_NAMES.map((toolName) => [toolName, 'channel'])),
};
