import type { ChannelDescriptor } from './descriptors-types.js';
import {
  COMMON_CHANNEL_TOOLS,
  DEFAULT_AGENT_TOOLS,
  FEISHU_CHANNEL_TOOLS,
  INBOUND_SECRET_FIELD,
  MEMBER_ACL_JSON_FIELD,
  REQUIRE_MENTION_IN_GROUP_FIELD,
  WEIXIN_CHANNEL_TOOLS,
  WS_RELAY_FIELD,
} from './descriptors-shared.js';
import { CHANNEL_QUICK_LINKS } from './descriptors-links.js';

export const CHINA_CHANNEL_DESCRIPTORS: ChannelDescriptor[] = [
  {
    type: 'feishu',
    displayName: '飞书 Bot',
    description: '适用于飞书 / Lark 机器人接入，支持群聊列表拉取与卡片式回复。',
    icon: 'feishu',
    category: 'china',
    tools: [...DEFAULT_AGENT_TOOLS, ...FEISHU_CHANNEL_TOOLS],
    quickLinks: CHANNEL_QUICK_LINKS.feishu,
    configSchema: [
      {
        key: 'appId',
        label: 'App ID',
        type: 'text',
        required: true,
        placeholder: 'cli_xxxxx',
      },
      {
        key: 'appSecret',
        label: 'App Secret',
        type: 'secret',
        required: true,
      },
      {
        key: 'verificationToken',
        label: 'Verification Token',
        type: 'text',
        placeholder: '可选，用于回调校验',
      },
      {
        key: 'botOpenId',
        label: 'Bot Open ID',
        type: 'text',
        placeholder: '可选，用于群聊 @ 机器人过滤',
      },
      {
        key: 'encryptKey',
        label: 'Encrypt Key',
        type: 'secret',
        placeholder: '可选，用于事件加密',
      },
      MEMBER_ACL_JSON_FIELD,
      INBOUND_SECRET_FIELD,
      WS_RELAY_FIELD,
    ],
  },
  {
    type: 'dingtalk',
    displayName: '钉钉 Bot',
    description: '支持机器人 Webhook 与企业应用两种接入方式。',
    icon: 'dingtalk',
    category: 'china',
    tools: [...DEFAULT_AGENT_TOOLS, ...COMMON_CHANNEL_TOOLS],
    quickLinks: CHANNEL_QUICK_LINKS.dingtalk,
    configSchema: [
      {
        key: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        placeholder: 'https://oapi.dingtalk.com/robot/send?...',
        description: '如使用自定义机器人，可仅填写 Webhook 配置。',
      },
      {
        key: 'secret',
        label: 'Webhook Secret',
        type: 'secret',
      },
      {
        key: 'appKey',
        label: 'App Key',
        type: 'text',
        description: '如使用企业应用机器人，请填写 App Key / App Secret / Robot Code。',
      },
      {
        key: 'appSecret',
        label: 'App Secret',
        type: 'secret',
      },
      {
        key: 'robotCode',
        label: 'Robot Code',
        type: 'text',
      },
      {
        key: 'cardTemplateId',
        label: 'AI Card Template ID',
        type: 'text',
        description: '可选，填写后钉钉回复会使用互动卡片进行流式更新。',
      },
      MEMBER_ACL_JSON_FIELD,
      INBOUND_SECRET_FIELD,
      WS_RELAY_FIELD,
    ],
  },
  {
    type: 'weixin',
    displayName: '微信公众平台',
    description: '微信公众平台 iLink Bot 接入，支持长轮询收取用户消息并回复现有会话。',
    icon: 'weixin',
    category: 'china',
    tools: [...DEFAULT_AGENT_TOOLS, ...WEIXIN_CHANNEL_TOOLS],
    quickLinks: CHANNEL_QUICK_LINKS.weixin,
    configSchema: [
      {
        key: 'token',
        label: 'Bot Token',
        type: 'secret',
        description: '可通过下方扫码绑定自动填入；已有凭证时也可手动填写。',
      },
      {
        key: 'accountId',
        label: 'Account ID',
        type: 'text',
        description: '用于区分上下文 token 缓存的公众号账号标识。',
      },
      {
        key: 'baseUrl',
        label: 'Base URL',
        type: 'text',
        placeholder: 'https://ilinkai.weixin.qq.com',
      },
      {
        key: 'routeTag',
        label: 'Route Tag',
        type: 'text',
        description: '可选，透传到 SKRouteTag 请求头。',
      },
      MEMBER_ACL_JSON_FIELD,
      INBOUND_SECRET_FIELD,
      WS_RELAY_FIELD,
    ],
  },
  {
    type: 'wecom',
    displayName: '企业微信 Bot',
    description: '支持企业微信应用消息与群机器人 Webhook 两种模式。',
    icon: 'wecom',
    category: 'china',
    tools: [...DEFAULT_AGENT_TOOLS, ...COMMON_CHANNEL_TOOLS],
    quickLinks: CHANNEL_QUICK_LINKS.wecom,
    configSchema: [
      {
        key: 'corpId',
        label: 'Corp ID',
        type: 'text',
        description: '应用模式下需要 corpId / corpSecret / agentId。',
      },
      {
        key: 'corpSecret',
        label: 'Corp Secret',
        type: 'secret',
      },
      {
        key: 'agentId',
        label: 'Agent ID',
        type: 'text',
      },
      {
        key: 'webhookUrl',
        label: 'Webhook URL',
        type: 'text',
        placeholder: 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?...',
        description: '群机器人模式下可仅填写 Webhook URL。',
      },
      {
        key: 'botName',
        label: 'Bot Name',
        type: 'text',
        placeholder: 'OpenAWork Bot',
        description: '可选；用于企业微信群聊中的 @ 文本识别。',
      },
      MEMBER_ACL_JSON_FIELD,
      REQUIRE_MENTION_IN_GROUP_FIELD,
      INBOUND_SECRET_FIELD,
      WS_RELAY_FIELD,
    ],
  },
  {
    type: 'qq',
    displayName: 'QQ Bot',
    description: '腾讯 QQ 机器人接入，适合频道与群消息投递。',
    icon: 'qq',
    category: 'china',
    tools: [...DEFAULT_AGENT_TOOLS, ...COMMON_CHANNEL_TOOLS],
    quickLinks: CHANNEL_QUICK_LINKS.qq,
    configSchema: [
      {
        key: 'appId',
        label: 'App ID',
        type: 'text',
        required: true,
      },
      {
        key: 'clientSecret',
        label: 'Client Secret',
        type: 'secret',
        required: true,
      },
      {
        key: 'webhookSecret',
        label: 'Webhook Secret',
        type: 'secret',
        placeholder: '可选，用于回调验签',
      },
      {
        key: 'gatewayUrl',
        label: 'Gateway URL',
        type: 'text',
        placeholder: '可选，留空则自动从 QQ API 获取',
        description: '用于测试或私有中转；生产环境通常留空，后端会调用 QQ /gateway 获取。',
      },
      {
        key: 'useSandbox',
        label: 'Use Sandbox',
        type: 'text',
        placeholder: 'true / false',
        description: '填 true 时使用 QQ sandbox API；留空或 false 使用生产 API。',
      },
      {
        key: 'markdownSupport',
        label: 'Markdown Support',
        type: 'text',
        placeholder: 'true / false',
        description: '填 true 时 C2C 消息按 QQ Markdown 能力发送。',
      },
      MEMBER_ACL_JSON_FIELD,
      INBOUND_SECRET_FIELD,
      WS_RELAY_FIELD,
    ],
  },
];
