import { StyleSheet } from 'react-native';
import { colors } from '../../theme/colors';
import { radii } from '../../theme/radii';
import { textPresets } from '../../theme/typography';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bgBase },
  messageList: { flex: 1 },
  list: { paddingHorizontal: 16, paddingTop: 8, paddingBottom: 12, gap: 8 },
  empty: { ...textPresets.body, color: colors.textMuted, textAlign: 'center', marginTop: 60 },
  inputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    minHeight: 40,
    borderRadius: 14,
    backgroundColor: colors.surface2,
    paddingHorizontal: 10,
  },
  input: {
    flex: 1,
    backgroundColor: colors.transparent,
    color: colors.textStrong,
    borderRadius: 14,
    paddingHorizontal: 0,
    paddingVertical: 8,
    fontSize: 14,
    maxHeight: 120,
    borderWidth: 0,
  },
  sendBtn: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sendBtnDisabled: { opacity: 0.4 },
  sendBtnText: { color: colors.white, fontSize: 20, fontWeight: '700', lineHeight: 22 },

  /* Chat Header */
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 44,
    paddingHorizontal: 12,
  },
  headerBackBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  chatHeaderTitle: {
    ...textPresets.cardTitle,
    color: colors.textStrong,
    flex: 1,
    textAlign: 'center',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 4,
  },
  headerActionBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },

  /* Context Bar */
  contextBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 6,
  },
  contextPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    backgroundColor: colors.surface2,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineSubtle,
    paddingHorizontal: 9,
    paddingVertical: 5,
  },
  contextPillActive: {
    backgroundColor: colors.contrastMuted,
    borderColor: colors.contrastBorder,
  },
  contextPillText: {
    ...textPresets.caption,
    color: colors.textMuted,
    fontWeight: '600',
  },

  /* Composer Card */
  composerCard: {
    backgroundColor: colors.surface1,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    marginHorizontal: 16,
    marginTop: 8,
    // marginBottom is applied dynamically via composerBottomInset
    // (tracks keyboard height / home indicator).
    padding: 10,
    gap: 6,
  },

  /* Quick templates */
  quickTemplateRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  quickLabel: {
    ...textPresets.caption,
    color: colors.textMuted,
    fontWeight: '800',
  },
  quickChip: {
    backgroundColor: colors.surface2,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  quickChipText: {
    ...textPresets.caption,
    color: colors.textDefault,
    fontWeight: '700',
  },
  toolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.lineDefault,
  },
  imageModeToggle: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    backgroundColor: colors.surface2,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  imageModeToggleActive: {
    borderColor: colors.contrastBorder,
    backgroundColor: colors.contrastMuted,
  },
  searchToggleActive: {
    borderColor: colors.warningBorder,
    backgroundColor: colors.warningMuted,
  },
  imageModeToggleDisabled: { opacity: 0.45 },
  imageModeToggleText: { ...textPresets.label, color: colors.textMuted },
  imageModeToggleTextActive: { color: colors.contrast },
  searchToggleTextActive: { color: colors.warning },
  modeHintBar: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: colors.lineSubtle,
    backgroundColor: colors.surfaceSoft,
  },
  modeHintText: { ...textPresets.caption, color: colors.textMuted, lineHeight: 15 },
  iconBtn: {
    width: 36,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  iconBtnText: { fontSize: 18 },
  historySection: {
    borderTopWidth: 1,
    borderTopColor: colors.lineDefault,
    paddingTop: 6,
  },
  historyTitle: {
    ...textPresets.label,
    color: colors.textMuted,
    paddingHorizontal: 12,
    marginBottom: 2,
  },
  composerMetaBar: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 10,
    paddingHorizontal: 12,
    paddingTop: 7,
    paddingBottom: 4,
    borderTopWidth: 1,
    borderTopColor: colors.lineDefault,
    backgroundColor: colors.bgBase,
  },
  composerMetaText: { flex: 1, ...textPresets.caption, color: colors.textMuted, lineHeight: 15 },
  composerMetaAction: { ...textPresets.caption, color: colors.danger, fontWeight: '800' },
  promptTemplateBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: colors.bgBase,
  },
  promptTemplateLabel: { ...textPresets.caption, color: colors.textSubtle, fontWeight: '800' },
  promptTemplateChip: {
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    backgroundColor: colors.surface2,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  promptTemplateChipDisabled: { opacity: 0.45 },
  promptTemplateChipText: {
    ...textPresets.bodySmall,
    color: colors.textDefault,
    fontWeight: '700',
  },
  streamErrorBar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 12,
    marginTop: 8,
    marginBottom: 4,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.dangerBorder,
    backgroundColor: colors.dangerMuted,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  streamErrorIcon: {
    width: 18,
    height: 18,
    borderRadius: 9,
    overflow: 'hidden',
    backgroundColor: colors.dangerMuted,
    color: colors.danger,
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 18,
    textAlign: 'center',
  },
  streamErrorText: { flex: 1, ...textPresets.bodySmall, color: colors.danger, lineHeight: 17 },
  streamErrorDismiss: { ...textPresets.label, color: colors.danger, fontWeight: '700' },
  streamErrorRetry: { ...textPresets.label, color: colors.danger, fontWeight: '800' },
  streamErrorRetryDisabled: { opacity: 0.45 },
  restoreFocusButton: {
    alignSelf: 'center',
    zIndex: 10,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.accentBorder,
    backgroundColor: colors.accentMuted,
    paddingHorizontal: 12,
    paddingVertical: 7,
    marginBottom: 8,
  },
  restoreFocusText: { ...textPresets.label, color: colors.accent, fontWeight: '700' },
  imagePanel: {
    marginHorizontal: 12,
    marginTop: 10,
    marginBottom: 8,
    borderRadius: radii.lg,
    borderWidth: 1,
    borderColor: colors.contrastBorder,
    backgroundColor: colors.contrastMuted,
    padding: 12,
    gap: 8,
  },
  imagePanelTitle: { ...textPresets.body, color: colors.textDefault, fontWeight: '700' },
  imagePanelText: { ...textPresets.bodySmall, color: colors.textDefault, lineHeight: 18 },
  imagePanelHint: { ...textPresets.caption, color: colors.textMuted, lineHeight: 16 },
  imagePanelHintDanger: { color: colors.danger },
  imagePresetGroups: { gap: 10 },
  imagePresetGroup: { gap: 6 },
  imagePresetGroupTitle: { ...textPresets.label, color: colors.textDefault },
  imagePresetGroupHint: { ...textPresets.caption, color: colors.textMuted, lineHeight: 16 },
  imageOptionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  optionChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    backgroundColor: colors.surface2,
  },
  optionChipActive: { borderColor: colors.contrastBorder, backgroundColor: colors.contrastMuted },
  optionChipText: { ...textPresets.caption, color: colors.textMuted },
  optionChipTextActive: { color: colors.contrast, fontWeight: '600' },
  imagePreviewLoadingLayer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  imagePreviewLoadingPill: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    borderRadius: radii.pill,
    borderWidth: 1,
    borderColor: colors.lineDefault,
    backgroundColor: colors.surfaceGlass,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  imagePreviewLoadingText: { ...textPresets.label, color: colors.textDefault },
});
